---

- name: Add Group
  group:
    name="{{ mirror_unix_group }}"
    state="present"

- name: Add User
  user:
    name="{{ mirror_unix_user }}"
    group="{{ mirror_unix_group }}"
    home="{{ mirror_unix_home }}"
    move_home="yes"
    shell="{{ mirror_unix_shell }}"
    state="present"

- name: Ensure Proper Owner of Home Directory
  file:
    path="{{ mirror_unix_home }}"
    owner="{{ mirror_unix_user }}"
    group="{{ mirror_unix_user }}"
    mode=2751

- name: Make Sure Doc Root Exists
  file:
    path="{{ mirror_doc_root }}"
    owner="{{ mirror_unix_user }}"
    group="{{ mirror_unix_user }}"
    state="directory"
    mode=2751

- name: Make Sure Cron Dir Exists
  file:
    path="{{ mirror_cron_dir }}"
    owner="{{ mirror_unix_user }}"
    group="{{ mirror_unix_user }}"
    state="directory"
    mode=0700
