---

- name: Add Group
  group:
    name="{{ mirror_unix_group }}"
    state="present"

- name: Add User
  user:
    name="{{ mirror_unix_user }}"
    group="{{ mirror_unix_group }}"
    groups="sshusers"
    home="{{ mirror_unix_home }}"
    move_home="yes"
    shell="{{ mirror_unix_shell }}"
    state="present"

- name: Ensure Proper Owner of Home Directory
  file:
    path="{{ mirror_unix_home }}"
    owner="{{ mirror_unix_user }}"
    group="{{ mirror_unix_user }}"
    mode=2751

- name: Make Sure Doc Root Exists
  file:
    path="{{ mirror_doc_root }}"
    owner="{{ mirror_unix_user }}"
    group="{{ mirror_unix_user }}"
    state="directory"
    mode=2755

- name: Make Sure Cron Dir Exists
  file:
    path="{{ mirror_cron_dir }}"
    owner="{{ mirror_unix_user }}"
    group="{{ mirror_unix_user }}"
    state="directory"
    mode=0700

- name: Setup Directory Size CRON
  cron:
    name="DIRECTORY_SIZES.TXT"
    minute="0"
    hour="4"
    job="date >{{ mirror_doc_root }}/DIRECTORY_SIZES.TXT ; du -hsc {{ mirror_doc_root }}/*/ >>{{ mirror_doc_root }}/DIRECTORY_SIZES.TXT"
    state="present"

- name: Add Our Key to Auth Users
  authorized_key:
    user="{{ mirror_unix_user }}"
    state="present"
    key="{{ mirror_ssh_pub_key }}"
  when: mirror_ssh_pub_key != ""

- name: Output Our Private Key
  copy:
    content="{{ mirror_ssh_priv_key }}"
    dest="{{ mirror_unix_home }}/.ssh/id_rsa"
    owner="{{ mirror_unix_user }}"
    group="{{ mirror_unix_group }}"
    mode="0600"
  no_log: true
  when: mirror_ssh_priv_key != ""

- name: Install Mirror Contact
  template:
    src="MIRROR_CONTACT.TXT.j2"
    dest="{{ mirror_doc_root }}/MIRROR_CONTACT.TXT"
    owner="{{ mirror_unix_user }}"
    group="{{ mirror_unix_group }}"
    mode="0644"
